use ns_sir::decl::{SirDecl, SirImplTarget, SirProgram};
use ns_sir::expr::{SirExpr, SirLiteral, SirTemplatePart};
use ns_sir::ids::{SirClassId, SirEnumId, SirFieldId, SirFnId, SirTypeId, SirValueId};
use ns_sir::stmt::SirStmt;
use ns_sir::types::SirType;
use std::collections::BTreeSet;

pub fn generate_rust(program: &SirProgram) -> String {
    RustGenerator::new(program).generate()
}

struct RustGenerator<'a> {
    program: &'a SirProgram,
    output: String,
    indent: usize,
}

impl<'a> RustGenerator<'a> {
    fn new(program: &'a SirProgram) -> Self {
        Self {
            program,
            output: String::new(),
            indent: 0,
        }
    }

    fn generate(mut self) -> String {
        self.line("// Generated by ns-codegen from ns-sir.");
        self.line("");

        for import in &self.program.imports {
            self.line(&format!(
                "// import {} from {}",
                import.local_name, import.from_module_path
            ));
        }
        if !self.program.imports.is_empty() {
            self.line("");
        }

        for decl in &self.program.decls {
            self.gen_decl(decl);
            self.line("");
        }

        self.emit_rust_entrypoint_wrapper_if_needed();

        self.output
    }

    fn gen_decl(&mut self, decl: &SirDecl) {
        match decl {
            SirDecl::Error => self.line("// <sir error decl>"),
            SirDecl::Const { value, expr } => {
                let name = self.value_name(*value);
                let ty = self.value_type(*value);
                let init = self.gen_expr(expr);
                self.line(&format!("pub const {name}: {ty} = {init};"));
            }
            SirDecl::Function { id, body } => self.gen_function(*id, body),
            SirDecl::TypeAlias { name, ty } => {
                let target = self.type_to_rust(*ty);
                self.line(&format!("pub type {name} = {target};"));
            }
            SirDecl::Class {
                id,
                fields,
                methods,
                constructor,
            } => self.gen_class(*id, fields, methods, *constructor),
            SirDecl::Enum { id } => self.gen_enum(*id),
            SirDecl::Impl { target, methods } => self.gen_impl(*target, methods),
        }
    }

    fn gen_function(&mut self, id: SirFnId, body: &[SirStmt]) {
        let Some(symbol) = self.program.functions.get(id.0 as usize) else {
            self.line("// <missing function symbol>");
            return;
        };
        let params = symbol
            .params
            .iter()
            .map(|param| format!("{}: {}", self.value_name(*param), self.value_type(*param)))
            .collect::<Vec<_>>()
            .join(", ");
        let ret = symbol
            .ret
            .map(|t| self.type_to_rust(t))
            .unwrap_or_else(|| "()".to_string());
        let generics = self.render_fn_generics(&symbol.params, symbol.ret);
        let rendered_name = if self.should_rename_main(symbol) {
            "ns_main".to_string()
        } else {
            self.sanitize_ident(&symbol.name)
        };
        self.line(&format!(
            "pub fn {}{generics}({params}) -> {ret} {{",
            rendered_name
        ));
        self.indent += 1;
        self.gen_stmts(body);
        self.indent -= 1;
        self.line("}");
    }

    fn gen_class(
        &mut self,
        id: SirClassId,
        fields: &[SirFieldId],
        methods: &[SirFnId],
        constructor: Option<SirFnId>,
    ) {
        let Some(class) = self.program.classes.get(id.0 as usize) else {
            self.line("// <missing class symbol>");
            return;
        };

        self.line("#[derive(Debug, Clone)]");
        self.line(&format!("pub struct {} {{", class.name));
        self.indent += 1;
        for field_id in fields {
            let Some(field) = self.program.fields.get(field_id.0 as usize) else {
                self.line("// <missing field symbol>");
                continue;
            };
            let ty = field
                .ty
                .map(|t| self.type_to_rust(t))
                .unwrap_or_else(|| "()".to_string());
            self.line(&format!("pub {}: {},", field.name, ty));
        }
        self.indent -= 1;
        self.line("}");
        self.line("");

        self.line(&format!("impl {} {{", class.name));
        self.indent += 1;

        if let Some(ctor) = constructor {
            self.gen_associated_fn(ctor, "new");
            self.line("");
        }

        for (idx, method) in methods.iter().enumerate() {
            self.gen_associated_fn(*method, &self.fn_name(*method));
            if idx + 1 != methods.len() {
                self.line("");
            }
        }
        self.indent -= 1;
        self.line("}");

        if let Some(parent) = class.inherited_class {
            let parent_name = self.class_name(parent);
            self.line("");
            self.line(&format!(
                "// NOTE: {} extends {} in source SIR.",
                class.name, parent_name
            ));
        }
    }

    fn gen_enum(&mut self, id: SirEnumId) {
        let Some(en) = self.program.enums.get(id.0 as usize) else {
            self.line("// <missing enum symbol>");
            return;
        };
        self.line("#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
        self.line(&format!("pub enum {} {{", en.name));
        self.indent += 1;
        for member in &en.members {
            self.line(&format!("{member},"));
        }
        self.indent -= 1;
        self.line("}");
    }

    fn gen_impl(&mut self, target: SirImplTarget, methods: &[SirFnId]) {
        let target_name = match target {
            SirImplTarget::Class(id) => self.class_name(id),
            SirImplTarget::Enum(id) => self.enum_name(id),
        };
        self.line(&format!("impl {target_name} {{"));
        self.indent += 1;
        for (idx, method) in methods.iter().enumerate() {
            self.gen_associated_fn(*method, &self.fn_name(*method));
            if idx + 1 != methods.len() {
                self.line("");
            }
        }
        self.indent -= 1;
        self.line("}");
    }

    fn gen_associated_fn(&mut self, id: SirFnId, rendered_name: &str) {
        let Some(symbol) = self.program.functions.get(id.0 as usize) else {
            self.line("// <missing associated function symbol>");
            return;
        };
        let params = symbol
            .params
            .iter()
            .map(|param| format!("{}: {}", self.value_name(*param), self.value_type(*param)))
            .collect::<Vec<_>>()
            .join(", ");
        let ret = symbol
            .ret
            .map(|t| self.type_to_rust(t))
            .unwrap_or_else(|| "()".to_string());
        let generics = self.render_fn_generics(&symbol.params, symbol.ret);

        let body = self
            .program
            .decls
            .iter()
            .find_map(|decl| match decl {
                SirDecl::Function { id: fn_id, body } if *fn_id == id => Some(body.as_slice()),
                _ => None,
            })
            .unwrap_or(&[]);

        self.line(&format!(
            "pub fn {}{generics}({params}) -> {ret} {{",
            self.sanitize_ident(rendered_name)
        ));
        self.indent += 1;
        self.gen_stmts(body);
        self.indent -= 1;
        self.line("}");
    }

    fn gen_stmts(&mut self, body: &[SirStmt]) {
        if body.is_empty() {
            self.line("()");
            return;
        }
        for stmt in body {
            self.gen_stmt(stmt);
        }
    }

    fn gen_stmt(&mut self, stmt: &SirStmt) {
        match stmt {
            SirStmt::Error => self.line("panic!(\"sir error stmt\");"),
            SirStmt::InitParent { class_id } => {
                self.line(&format!("// init parent {}", self.class_name(*class_id)));
            }
            SirStmt::InitField { field_id } => {
                let field_name = self
                    .program
                    .fields
                    .get(field_id.0 as usize)
                    .map(|f| f.name.as_str())
                    .unwrap_or("unknown_field");
                self.line(&format!("// init field {field_name}"));
            }
            SirStmt::Expr(expr) => match expr {
                SirExpr::IntrinsicPrintln { args, .. } => self.gen_intrinsic_println(args),
                _ => self.line(&format!("{};", self.gen_expr(expr))),
            },
            SirStmt::Let {
                value,
                is_mut,
                init,
            } => {
                let name = self.value_name(*value);
                let ty = self.value_type(*value);
                let binding_kw = if *is_mut { "let mut" } else { "let" };
                if let Some(expr) = init {
                    self.line(&format!("{binding_kw} {name}: {ty} = {};", self.gen_expr(expr)));
                } else {
                    self.line(&format!("{binding_kw} {name}: {ty};"));
                }
            }
            SirStmt::Assign { target, value } => {
                self.line(&format!("{} = {};", self.gen_expr(target), self.gen_expr(value)));
            }
            SirStmt::Return(expr) => {
                if let Some(expr) = expr {
                    self.line(&format!("return {};", self.gen_expr(expr)));
                } else {
                    self.line("return;");
                }
            }
            SirStmt::If {
                test,
                then_body,
                else_body,
            } => {
                self.line(&format!("if {} {{", self.gen_expr(test)));
                self.indent += 1;
                self.gen_stmts(then_body);
                self.indent -= 1;
                if else_body.is_empty() {
                    self.line("}");
                } else {
                    self.line("} else {");
                    self.indent += 1;
                    self.gen_stmts(else_body);
                    self.indent -= 1;
                    self.line("}");
                }
            }
            SirStmt::Loop { body } => {
                self.line("loop {");
                self.indent += 1;
                self.gen_stmts(body);
                self.indent -= 1;
                self.line("}");
            }
            SirStmt::Break => self.line("break;"),
        }
    }

    fn gen_expr(&self, expr: &SirExpr) -> String {
        match expr {
            SirExpr::Error { .. } => "panic!(\"sir error expr\")".to_string(),
            SirExpr::Literal { lit, .. } => self.literal_to_rust(lit),
            SirExpr::ValueRef { value, .. } => self.value_name(*value),
            SirExpr::TypeRef { type_id, .. } => self.type_to_rust(*type_id),
            SirExpr::Call {
                callee,
                type_args: _,
                args,
                ..
            } => {
                let fn_name = callee
                    .and_then(|id| self.program.functions.get(id.0 as usize))
                    .map(|f| f.name.as_str())
                    .unwrap_or("");
                let args = args
                    .iter()
                    .map(|arg| self.gen_expr(arg))
                    .collect::<Vec<_>>()
                    .join(", ");
                if fn_name.is_empty() {
                    "panic!(\"sir unresolved callee\")".to_string()
                } else {
                    format!("{}({args})", self.sanitize_ident(fn_name))
                }
            }
            SirExpr::IntrinsicPrintln { .. } => "panic!(\"println intrinsic in expression position\")".to_string(),
            SirExpr::TemplateString { parts, .. } => {
                let mut rendered = String::new();
                for part in parts {
                    match part {
                        SirTemplatePart::Text(text) => rendered.push_str(text),
                        SirTemplatePart::Expr(_) => rendered.push_str("<expr>"),
                    }
                }
                format!("{rendered:?}")
            }
            SirExpr::Unary { op, value, .. } => {
                let op = self.map_unary_op(op);
                let value = self.gen_expr(value);
                if self.is_fallback_expr(&value) {
                    "panic!(\"sir invalid unary operand\")".to_string()
                } else {
                    format!("({op}{value})")
                }
            }
            SirExpr::Binary {
                op, left, right, ..
            } => {
                let op = self.map_binary_op(op);
                let left = self.gen_expr(left);
                let right = self.gen_expr(right);
                if self.is_fallback_expr(&left) || self.is_fallback_expr(&right) {
                    "panic!(\"sir invalid binary operands\")".to_string()
                } else {
                    format!("({left} {op} {right})")
                }
            }
            SirExpr::Member {
                object, property, ..
            } => {
                format!("{}.{}", self.gen_expr(object), property)
            }
            SirExpr::StructLiteral {
                type_name, fields, ..
            } => {
                let fields = fields
                    .iter()
                    .map(|(name, expr)| format!("{name}: {}", self.gen_expr(expr)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{type_name} {{ {fields} }}")
            }
            SirExpr::New {
                class_name, args, ..
            } => {
                let args = args
                    .iter()
                    .map(|arg| self.gen_expr(arg))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{class_name}::new({args})")
            }
        }
    }

    fn literal_to_rust(&self, lit: &SirLiteral) -> String {
        match lit {
            SirLiteral::Number(value) => value.clone(),
            SirLiteral::String(value) => format!("{value:?}"),
            SirLiteral::Boolean(value) => value.to_string(),
        }
    }

    fn type_to_rust(&self, type_id: SirTypeId) -> String {
        let Some(ty) = self.program.types.get(type_id.0 as usize) else {
            return "()".to_string();
        };
        match ty {
            SirType::Error => "()".to_string(),
            SirType::Named { name, args } => {
                let mapped = Self::map_primitive_type(name);
                if args.is_empty() {
                    mapped.to_string()
                } else {
                    let args = args
                        .iter()
                        .map(|arg| self.type_to_rust(*arg))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{mapped}<{args}>")
                }
            }
            SirType::Dynamic { .. } => "Box<dyn core::any::Any>".to_string(),
            SirType::TypeParam { name } => name.clone(),
        }
    }

    fn map_primitive_type(ty: &str) -> &str {
        match ty {
            "i32" | "i64" | "u32" | "u64" | "usize" | "isize" | "bool" | "String" | "str"
            | "f32" | "f64" => ty,
            "void" => "()",
            _ => ty,
        }
    }

    fn class_name(&self, id: SirClassId) -> String {
        self.program
            .classes
            .get(id.0 as usize)
            .map(|c| c.name.clone())
            .unwrap_or_else(|| "UnknownClass".to_string())
    }

    fn enum_name(&self, id: SirEnumId) -> String {
        self.program
            .enums
            .get(id.0 as usize)
            .map(|e| e.name.clone())
            .unwrap_or_else(|| "UnknownEnum".to_string())
    }

    fn fn_name(&self, id: SirFnId) -> String {
        self.program
            .functions
            .get(id.0 as usize)
            .map(|f| f.name.clone())
            .unwrap_or_else(|| "unknown_fn".to_string())
    }

    fn value_name(&self, id: SirValueId) -> String {
        self.program
            .values
            .get(id.0 as usize)
            .map(|v| v.name.clone())
            .unwrap_or_else(|| "unknown_value".to_string())
    }

    fn value_type(&self, id: SirValueId) -> String {
        self.program
            .values
            .get(id.0 as usize)
            .and_then(|v| v.ty)
            .map(|t| self.type_to_rust(t))
            .unwrap_or_else(|| "()".to_string())
    }

    fn line(&mut self, s: &str) {
        self.output.push_str(&"    ".repeat(self.indent));
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn emit_rust_entrypoint_wrapper_if_needed(&mut self) {
        let Some(main_symbol) = self
            .program
            .functions
            .iter()
            .find(|f| self.sanitize_ident(&f.name) == "main")
        else {
            return;
        };

        if !self.should_rename_main(main_symbol) {
            return;
        }

        let ret = main_symbol
            .ret
            .map(|t| self.type_to_rust(t))
            .unwrap_or_else(|| "()".to_string());

        self.line("fn main() {");
        self.indent += 1;
        if ret == "i32" {
            self.line("std::process::exit(ns_main());");
        } else {
            self.line("let _ = ns_main();");
        }
        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn should_rename_main(&self, symbol: &ns_sir::symbols::SirFunctionSymbol) -> bool {
        if self.sanitize_ident(&symbol.name) != "main" {
            return false;
        }
        if !symbol.params.is_empty() {
            return true;
        }
        let ret = symbol
            .ret
            .map(|t| self.type_to_rust(t))
            .unwrap_or_else(|| "()".to_string());
        ret != "()"
    }

    fn sanitize_ident(&self, name: &str) -> String {
        name.rsplit("::").next().unwrap_or(name).to_string()
    }

    fn map_binary_op(&self, op: &str) -> &str {
        match op {
            "Plus" => "+",
            "Minus" => "-",
            "Star" => "*",
            "Slash" => "/",
            "Percent" => "%",
            "Equals" => "==",
            "NotEquals" => "!=",
            "Less" => "<",
            "Greater" => ">",
            "LessEqual" => "<=",
            "GreaterEqual" => ">=",
            "And" => "&&",
            "Or" => "||",
            _ => "==",
        }
    }

    fn map_unary_op(&self, op: &str) -> &str {
        match op {
            "Not" => "!",
            "Minus" => "-",
            "Plus" => "+",
            "BitNot" => "!",
            _ => "!",
        }
    }

    fn render_fn_generics(&self, params: &[SirValueId], ret: Option<SirTypeId>) -> String {
        let mut set = BTreeSet::new();
        for param in params {
            if let Some(ty) = self
                .program
                .values
                .get(param.0 as usize)
                .and_then(|v| v.ty)
            {
                self.collect_type_params(ty, &mut set);
            }
        }
        if let Some(ret) = ret {
            self.collect_type_params(ret, &mut set);
        }
        if set.is_empty() {
            String::new()
        } else {
            format!(
                "<{}>",
                set.into_iter().collect::<Vec<_>>().join(", ")
            )
        }
    }

    fn collect_type_params(&self, ty: SirTypeId, out: &mut BTreeSet<String>) {
        let Some(node) = self.program.types.get(ty.0 as usize) else {
            return;
        };
        match node {
            SirType::TypeParam { name } => {
                out.insert(name.clone());
            }
            SirType::Named { name, args } => {
                if args.is_empty() && Self::looks_like_type_param_name(name) {
                    out.insert(name.clone());
                }
                for arg in args {
                    self.collect_type_params(*arg, out);
                }
            }
            SirType::Error | SirType::Dynamic { .. } => {}
        }
    }

    fn looks_like_type_param_name(name: &str) -> bool {
        name.len() == 1 && name.chars().all(|c| c.is_ascii_uppercase())
    }

    fn is_fallback_expr(&self, expr: &str) -> bool {
        expr.contains("panic!(")
    }

    fn gen_intrinsic_println(&mut self, args: &[SirExpr]) {
        if args.is_empty() {
            self.line("println!();");
            return;
        }

        let mut format_string = String::new();
        let mut format_args = Vec::new();

        for (idx, arg) in args.iter().enumerate() {
            if idx > 0 {
                format_string.push(' ');
            }

            match arg {
                SirExpr::TemplateString { parts, .. } => {
                    for part in parts {
                        match part {
                            SirTemplatePart::Text(text) => {
                                format_string.push_str(&Self::escape_rust_format_text(text));
                            }
                            SirTemplatePart::Expr(expr) => {
                                format_string.push_str("{:?}");
                                format_args.push(self.gen_expr(expr));
                            }
                        }
                    }
                }
                _ => {
                    format_string.push_str("{:?}");
                    format_args.push(self.gen_expr(arg));
                }
            }
        }

        if format_args.is_empty() {
            self.line(&format!("println!({format_string:?});"));
        } else {
            self.line(&format!(
                "println!({format_string:?}, {});",
                format_args.join(", ")
            ));
        }
    }

    fn escape_rust_format_text(text: &str) -> String {
        text.replace('{', "{{").replace('}', "}}")
    }
}

#[cfg(test)]
mod tests {
    use ns_sir::decl::{SirDecl, SirProgram};
    use ns_sir::expr::{SirExpr, SirLiteral};
    use ns_sir::ids::{SirClassId, SirFieldId, SirFnId, SirTypeId, SirValueId};
    use ns_sir::stmt::SirStmt;
    use ns_sir::symbols::{SirClassSymbol, SirEnumSymbol, SirFieldSymbol, SirFunctionSymbol, SirValueSymbol};
    use ns_sir::types::SirType;

    use super::generate_rust;

    #[test]
    fn generates_function_and_const() {
        let program = SirProgram {
            decls: vec![
                SirDecl::Const {
                    value: SirValueId(0),
                    expr: SirExpr::Literal {
                        lit: SirLiteral::Number("42".to_string()),
                        ty: Some(SirTypeId(0)),
                    },
                },
                SirDecl::Function {
                    id: SirFnId(0),
                    body: vec![SirStmt::Return(Some(SirExpr::ValueRef {
                        value: SirValueId(1),
                        ty: Some(SirTypeId(0)),
                    }))],
                },
            ],
            values: vec![
                SirValueSymbol {
                    id: SirValueId(0),
                    name: "ANSWER".to_string(),
                    ty: Some(SirTypeId(0)),
                },
                SirValueSymbol {
                    id: SirValueId(1),
                    name: "x".to_string(),
                    ty: Some(SirTypeId(0)),
                },
            ],
            functions: vec![SirFunctionSymbol {
                id: SirFnId(0),
                name: "id".to_string(),
                params: vec![SirValueId(1)],
                ret: Some(SirTypeId(0)),
            }],
            classes: vec![],
            enums: vec![],
            fields: vec![],
            traits: vec![],
            imports: vec![],
            exports: vec![],
            types: vec![SirType::Named {
                name: "i32".to_string(),
                args: vec![],
            }],
        };

        let rust = generate_rust(&program);
        assert!(rust.contains("pub const ANSWER: i32 = 42;"));
        assert!(rust.contains("pub fn id(x: i32) -> i32"));
        assert!(rust.contains("return x;"));
    }

    #[test]
    fn generates_class_and_methods() {
        let program = SirProgram {
            decls: vec![
                SirDecl::Class {
                    id: SirClassId(0),
                    fields: vec![SirFieldId(0)],
                    methods: vec![SirFnId(1)],
                    constructor: Some(SirFnId(0)),
                },
                SirDecl::Function {
                    id: SirFnId(0),
                    body: vec![SirStmt::Return(Some(SirExpr::StructLiteral {
                        type_name: "Point".to_string(),
                        fields: vec![(
                            "x".to_string(),
                            SirExpr::ValueRef {
                                value: SirValueId(0),
                                ty: Some(SirTypeId(0)),
                            },
                        )],
                        ty: None,
                    }))],
                },
                SirDecl::Function {
                    id: SirFnId(1),
                    body: vec![SirStmt::Return(Some(SirExpr::Member {
                        object: Box::new(SirExpr::ValueRef {
                            value: SirValueId(1),
                            ty: None,
                        }),
                        property: "x".to_string(),
                        ty: Some(SirTypeId(0)),
                    }))],
                },
            ],
            values: vec![
                SirValueSymbol {
                    id: SirValueId(0),
                    name: "x".to_string(),
                    ty: Some(SirTypeId(0)),
                },
                SirValueSymbol {
                    id: SirValueId(1),
                    name: "self_ref".to_string(),
                    ty: None,
                },
            ],
            functions: vec![
                SirFunctionSymbol {
                    id: SirFnId(0),
                    name: "Point_ctor".to_string(),
                    params: vec![SirValueId(0)],
                    ret: Some(SirTypeId(1)),
                },
                SirFunctionSymbol {
                    id: SirFnId(1),
                    name: "x".to_string(),
                    params: vec![SirValueId(1)],
                    ret: Some(SirTypeId(0)),
                },
            ],
            classes: vec![SirClassSymbol {
                id: SirClassId(0),
                name: "Point".to_string(),
                fields: vec![SirFieldId(0)],
                methods: vec![SirFnId(1)],
                inherited_class: None,
                implemented_traits: vec![],
                delegated_trait_impls: vec![],
            }],
            enums: vec![],
            fields: vec![SirFieldSymbol {
                id: SirFieldId(0),
                owner: SirClassId(0),
                name: "x".to_string(),
                ty: Some(SirTypeId(0)),
            }],
            traits: vec![],
            imports: vec![],
            exports: vec![],
            types: vec![
                SirType::Named {
                    name: "i32".to_string(),
                    args: vec![],
                },
                SirType::Named {
                    name: "Point".to_string(),
                    args: vec![],
                },
            ],
        };

        let rust = generate_rust(&program);
        assert!(rust.contains("pub struct Point"));
        assert!(rust.contains("pub x: i32,"));
        assert!(rust.contains("pub fn new(x: i32) -> Point"));
        assert!(rust.contains("pub fn x(self_ref: ()) -> i32"));
    }

    #[test]
    fn generates_control_flow() {
        let program = SirProgram {
            decls: vec![SirDecl::Function {
                id: SirFnId(0),
                body: vec![
                    SirStmt::Let {
                        value: SirValueId(0),
                        is_mut: true,
                        init: Some(SirExpr::Literal {
                            lit: SirLiteral::Boolean(true),
                            ty: Some(SirTypeId(0)),
                        }),
                    },
                    SirStmt::Loop {
                        body: vec![SirStmt::If {
                            test: SirExpr::ValueRef {
                                value: SirValueId(0),
                                ty: Some(SirTypeId(0)),
                            },
                            then_body: vec![SirStmt::Break],
                            else_body: vec![],
                        }],
                    },
                    SirStmt::Return(None),
                ],
            }],
            values: vec![SirValueSymbol {
                id: SirValueId(0),
                name: "done".to_string(),
                ty: Some(SirTypeId(0)),
            }],
            functions: vec![SirFunctionSymbol {
                id: SirFnId(0),
                name: "main".to_string(),
                params: vec![],
                ret: None,
            }],
            classes: vec![],
            enums: vec![SirEnumSymbol {
                id: ns_sir::ids::SirEnumId(0),
                name: "Unused".to_string(),
                members: vec![],
            }],
            fields: vec![],
            traits: vec![],
            imports: vec![],
            exports: vec![],
            types: vec![SirType::Named {
                name: "bool".to_string(),
                args: vec![],
            }],
        };

        let rust = generate_rust(&program);
        assert!(rust.contains("let mut done: bool = true;"));
        assert!(rust.contains("loop {"));
        assert!(rust.contains("if done {"));
        assert!(rust.contains("break;"));
    }
}
