#[derive(Debug, Copy, Clone, PartialEq)]
pub enum Keyword {
    Index,
    Import,
    Export,
    From,
    Function,
    Class,
    Interface,
    Extends,
    Implements,
    Dynamic,
    Const,
    Enum,
    Type,
    Let,
    Var,
    Own,
    Ref,
    Mut,
    If,
    Else,
    Return,
    Match,
    Loop,
    Break,
    /// Spelled bitwise AND (`bitand`); same name as `std::ops::BitAnd::bitand` in Rust.
    BitAnd,
}

pub fn keyword_to_token(ident: &str) -> Option<Keyword> {
    match ident {
        "index" => Some(Keyword::Index),
        "import" => Some(Keyword::Import),
        "export" => Some(Keyword::Export),
        "from" => Some(Keyword::From),
        "function" => Some(Keyword::Function),
        "class" => Some(Keyword::Class),
        "interface" => Some(Keyword::Interface),
        "extends" => Some(Keyword::Extends),
        "implements" => Some(Keyword::Implements),
        "dynamic" => Some(Keyword::Dynamic),
        "const" => Some(Keyword::Const),
        "enum" => Some(Keyword::Enum),
        "type" => Some(Keyword::Type),
        "let" => Some(Keyword::Let),
        "var" => Some(Keyword::Var),
        "own" => Some(Keyword::Own),
        "ref" => Some(Keyword::Ref),
        "mut" => Some(Keyword::Mut),
        "if" => Some(Keyword::If),
        "else" => Some(Keyword::Else),
        "return" => Some(Keyword::Return),
        "match" => Some(Keyword::Match),
        "loop" => Some(Keyword::Loop),
        "break" => Some(Keyword::Break),
        "bitand" => Some(Keyword::BitAnd),
        _ => None,
    }
}
